---
title: "REF 2021"
author: "PenguinJunk"
date: "2024-05-23"
output: html_document
---


```{r setup, include=FALSE}
library(readxl)
library(here)
library(tidyverse)
library(ggplot2)
library(ggsankey)
```

```{r readxls}
# read_excel reads both xls and xlsx files
REF.extract <- read_excel( "C:/Users/izzy_/OneDrive - University College London/thesis data files/REF 2021 Impact Case Studies - Extract - 2024-05-22.xlsx" )
```

```{r format}
UKcountries <- c("UK", "UK and Ireland", "Great Britain", "Cymru", "Scotland", "England")
assessmentunits <- c("Biological Sciences", "Earth Systems and Environmental Sciences", "Geography and Environmental Studies")
impacttypes <- c("Environmental", "Political", "Economic")
endeavourtypes <- c("Descriptive", "Analytic", "Prescriptive")
impactcat <- c("UK Gov", "UK governance", "UK organisations", "UK society", "other UK", "Int Gov", "Int governance", "Int organisations", "International", "commercial")

REF <- 
  REF.extract |>
  separate_longer_delim(cols = c(Countries), delim = ";") |> 
  separate_longer_delim(cols = c(Countries), delim = ",") |> 
  separate_longer_delim(cols = c(Countries), delim = ":") |> 
  mutate( Countries = str_remove_all(Countries, "\\["),
          Countries = str_remove_all(Countries, "]"),
          Countries = str_squish(Countries),
          Countries = str_replace_all(Countries, c("United Kingdom" = "UK",
                                                  "UNITED KINGDOM" = "UK",
                                                  "UK of Great Britain and Northern Ireland" = "UK",
                                                  "G3.1\\) UK" = "UK",
                                                  "G3.2\\) UK" = "UK",
                                                  "G3.3\\) UK" = "UK",
                                                  "G3.4\\) UK" = "UK",
                                                  "G3.5\\) UK" = "UK",
                                                  "Wales" = "Cymru"
                                                  )
                                     )
         ) |> 
  filter( Countries %in% UKcountries ) |> 
  mutate( Countries = factor(Countries, levels = UKcountries, ordered = TRUE)) |> 
  arrange(Countries) |> 
  distinct(`REF impact case study identifier`, .keep_all = TRUE) |> 
  mutate(Assessment_Unit = `Unit of assessment name`,
         Impact_Type = `Summary impact type`,
         Country = Countries, 
         Endeavour_Type = factor(Endeavour_Type, levels = endeavourtypes, ordered = TRUE),
         Impacted = `My category`,
         Impact_Summary = str_remove_all(`1. Summary of the impact`, "1. Summary of the impact"),
         Impact_Summary = str_remove_all(Impact_Summary, "1. Summary of Impact"),
         Impact_Summary = str_remove_all(Impact_Summary, "(indicative maximum 100 words)"),
         Impact_Summary = str_remove_all(Impact_Summary, "#"),
#         Impact_Summary = str_remove_all(Impact_Summary, "\\("),
#         Impact_Summary = str_remove_all(Impact_Summary, "\\)"),
         Impact_Summary = str_remove_all(Impact_Summary, "\\\\"),
         Impact_Summary = str_remove_all(Impact_Summary, "\\*"),
         Impact_Summary = str_remove_all(Impact_Summary, "1. Summary of the impact"),
         Impact_Summary = str_squish(str_remove_all(Impact_Summary, "\\(\\)"))
  )
```

```{r impacts}
impact_summaries <- 
  REF |> 
  select(Title, Impact_Summary)# 

impact_summaries |> 
  sample_n(1) |> 
  unite("text", 1:2, sep = "\n\n", remove = TRUE )|> 
  pull() |> 
  print()
```

```{r plot}

sankeylevels <- c(assessmentunits, impacttypes, endeavourtypes, impactcat)

REF_counts <- 
  REF |> 
  mutate(Impacted = str_replace_all(Impacted, "Int organisations", "International"),
         Impacted = str_replace_all(Impacted, "Int governance", "International"),
         Impacted = str_replace_all(Impacted, "Int Gov", "International"),
         Impacted = str_replace_all(Impacted, "UK society", "other UK"),
         Impacted = str_replace_all(Impacted, "UK organisations", "other UK"),
         Impacted = str_replace_all(Impacted, "UK governance", "other UK")
         ) |> 
  select(Assessment_Unit, Impact_Type, Country, Endeavour_Type, Impacted) |> 
  make_long(Assessment_Unit, Endeavour_Type, Impacted, Impact_Type) |> 
  mutate(node = factor(node, levels = sankeylevels))

nodenames <- c("Unit of assessment name", 
               "My endeavour Type", 
               "My impact category", 
               "Summary impact type")

ggplot(
  REF_counts,
  aes(
    x = x, next_x = next_x, node = node,
    next_node = next_node, fill = factor(node)
  )
) +
  geom_sankey(
    flow.alpha = .6,
    node.color = "gray30"
  ) +
  geom_sankey_label(
    aes(
      x = as.numeric(x) + .05,
      label = after_stat(paste0(node, "\nn = ", freq))
    ),
    size = 8 / .pt, color = "white", fill = "gray40",
    hjust = 0
  )  +
  scale_fill_viridis_d() +
  theme_sankey(base_size = 4) +
  scale_x_discrete(labels = nodenames) +
  theme(legend.position = "none",
        axis.text.x=element_text(size=10)) +
  guides(fill = guide_legend(ncol = 2))

ggsave(here("figures/REF_extract_sankey.png"), width = 10, height = 5)

```
